<?xml version="1.0" encoding="utf-8"?>

<Database Name="DocumentDB" Class="DocumentDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=DocumentDB;Integrated Security=True" SettingsObjectName="LinqToSqlXml.Properties.Settings" SettingsPropertyName="LinqToSqlXmlConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Documents" Member="Documents">
    <Type Name="Document">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DbName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CollectionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DocumentData" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>